### PR TITLE
update purs version and add tests

### PR DESCRIPTION
**Pull request by rubenpieters**
adapted code for newer purescript
added some simple tests
bumped version number

### CODE REVIEW

**Comment by fluffynukeit** [comment]
Sure, no problem.  I'm not maintaining this so if you want to take it over, feel free.  I'm also fine just merging PRs whenever they come in.  Thanks.

**Comment by rubenpieters** [comment]
Thanks for the fast merge. I wouldn't mind taking over, do I just change the `url` setting under `repository` in bower.json for that?

**Comment by fluffynukeit** [comment]
I actually don't know.  It's been so long since I did anything with purescript or bower.

A quick search shows that it would require that I unregister the package on bower and then you'd register your new one.  I think the same name is ok.  Code out there might break in the transition if it doesn't go smoothly...

To me, seems like more trouble than it's worth compared to merging PRs very occasionally.  The library's scope is so small I doubt there would be any changes except compatibility ones like you made.

**Comment by rubenpieters** [comment]
Sure, that makes sense.

**Pull request merged**
